"""auto migration

Revision ID: b30927c3ca2d
Revises: 
Create Date: 2025-09-09 15:48:14.771516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b30927c3ca2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrationform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ias_course', sa.Enum('IAS_111', 'IAS_121', 'IAS_131', 'IAS_212', 'IAS_321', 'IAS_322', 'IAS_330', 'IAS_430', name='iascourses'), nullable=True),
    sa.Column('university_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_type', sa.Enum('student', 'employee', 'employee_son', 'na', name='usertype'), nullable=False),
    sa.Column('academic_level', sa.Enum('orientation', 'freshman', 'sophomore', 'junior', 'senior', 'graduate', 'na', name='academiclevel'), nullable=False),
    sa.Column('how_heard', sa.Enum('social_media', 'ataa_community', 'email', 'other', name='howheard'), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrationform')
    # ### end Alembic commands ###
